import "@/app/assets/styles/globals.css";
import cn from "@/functions/cn";
import { Poppins } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const font = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" translate="no">
      <body className={cn(font.className, font.style, "antialiased")}>
        {children}
      </body>
    </html>
  );
}
